version: "2"

services:
  python_service:
    build: 
        context: .
        dockerfile: Dockerfile
    container_name: pythonApp_3
    privileged: true
    extra_hosts:
      - "github.global.ssl.fastly.net:151.101.185.194"
      - "github.com:192.30.253.112"
    volumes:
      - ../:/workspace
      - ~/.gitconfig:/root/.gitconfig
      - ~/.volumes/apps/pythonDev/.vscode-server:/root/.vscode-server
    command: sleep infinity
    ports:
      - 15000:5000
    environment:
      pwd: LocalHostPassWord123
      GOPATH: /go:/workspace
      MgoUser: kegel-admin
      MgoPwd: lsp123123
